[package]
name = "adventofcode2021rust"
version = "0.1.0"
edition = "2018"
authors = ["Daniel Low <daniellowtw@gmail.com>"]

[dependencies]
strum = "0.23"
strum_macros = "0.23"
itertools = "0.9.0"
itoa = "0.4.8"
image = "0.23.14"